### ISSUE TITLE
GPM installation not working

### ISSUE THREAD

**Issue by kiwiidb** [Regaez/grav-plugin-api#102]
**Describe the bug**
The installation usigin gpm does nothing.

**To Reproduce**
```
root@grav-84c9cc6cd9-w8ff7:/var/www/html# bin/gpm install api

GPM Releases Configuration: Stable


Nothing to install.
```

**Expected behavior**
Plugin should be installed

**Versions (please complete the following information):**
 - Grav:  v1.6.26
 - Grav Admin: v1.9.15

**Additional context**
Grav running inside a Docker container in our Kubernetes cluster.
Docker image: https://github.com/getgrav/docker-grav

**Comment by khanduras** [comment]
It's not on GPM yet

**Comment by kiwiidb** [comment]
Ok, thx for the response.
