### ISSUE TITLE
feat: access role permissions per endpoint/method

### ISSUE THREAD

**Issue by Regaez** [Regaez/grav-plugin-api#4]
It could be nice to allow the ability to specify roles for the API endpoints from within the plugin config. 

For example, a user might require the `admin.super` role in order to be able to use `DELETE /pages`, but does not require any role to use `GET /pages`

**Comment by Regaez** [comment]
Furthermore, it could be nice to have a generic `api.super` role that allows you to do _anything_ with the API, but have more specific `api.page.get` or `api.page.delete` etc to allow for fine-grained permissions. Possible scopes:

### Generic

- `api.super`|`admin.super`: allows access to everything

### Pages

- `api.pages.read`
- `api.pages.delete`
- `api.pages.edit`
- `api.pages.create`

### Users

- `api.users.read`
- `api.users.delete`
- `api.users.create`
- `api.users.edit`

### Plugins

- `api.plugins.read`
- `api.plugins.edit`
- `api.plugins.install`
- `api.plugins.uninstall`

### Configs

- `api.configs.read`
- `api.configs.edit`

**Comment by khanduras** [comment]
Data:
- api.data.read
- api.data.edit
